### ISSUE TITLE
出演団体一覧ページを完成させる。

### ISSUE THREAD

**Issue by tarou-jp** [Yadosai/official_site2024new#16]
<img width="166" alt="スクリーンショット 2024-04-14 18 26 26" src="https://github.com/Yadosai/official_site2024new/assets/117962902/1ecbb1f8-b020-46ec-befd-5a1ff1fa837a">

**Comment by tarou-jp** [comment]
引き継ぎ

**Comment by toratora-yaki** [comment]
不甲斐なくて申し訳ありません、よろしくお願いします

**Comment by tarou-jp** [comment]
もしかして、もうやってました？
アサイン解除してないだけだと思ってました...

**Comment by tarou-jp** [comment]
<img width="319" alt="スクリーンショット 2024-05-01 16 07 26" src="https://github.com/Yadosai/official_site2024new/assets/117962902/afba6ecf-b5cb-4e77-b6cb-e0a9420266fa">
検索は実装せずに形だけ作っちゃっいました

**Comment by toratora-yaki** [comment]
feature/#16-Create-performer-pageっていうブランチにコミットだけしてました、忙しいのに手間かけちゃってほんとに申し訳ない
