### ISSUE TITLE
トップページ最終調整

### ISSUE THREAD

**Issue by nowex35** [Yadosai/official_site2024new#52]
![スクリーンショット 2024-04-21 185433](https://github.com/Yadosai/official_site2024new/assets/152232532/6b050419-f7e4-4e75-8fd8-41b58d3fb327)

**Comment by tarou-jp** [comment]
文字サイズ％で指定すれば解決できそう

**Comment by nowex35** [comment]
おそらくある程度幅があるが（レスポンシブw950px以上）、縦が足りない13インチpc等でこの現象が起こります。あと、親要素が割合指定なんですがその子要素を割合指定って出来ましたっけ？

**Comment by tarou-jp** [comment]
どうやろ、widthとかの%指定は親要素が%だと使えないはずだけど,,

**Comment by tarou-jp** [comment]
これ、topページの最終調整用issueに変えられます？
他にも修正が必要な箇所が出てきたので

![image](https://github.com/Yadosai/official_site2024new/assets/117962902/32d1ec5d-85a2-42f0-ad07-a88e522a4df0)
上の時、画面がx方向にスクロールできること。

あと、このissueで画像も解像度高いやつに置き換えたい。

**Comment by nowex35** [comment]
・アイキャッチの文字が詰まる問題
・画面のサイズがずれていて横方向にスライドする問題
・画像の解像度の向上

**Comment by nowex35** [comment]
日付が間違っているところの修正
5/31,6/1

**Comment by toratora-yaki** [comment]
横にスクロールできる問題、layouts/default.vueのstyleタグにあるbodyに overflow-x: hidden; を追加したら改善するかもしれないです。

**Comment by tarou-jp** [comment]
ありがとうございます！
overflow-x:hidden;ってのは、はみ出した分を隠すってcssなので対症療法的な解決方法になるのかな。

footerとeyeCatchの画像がpcの横幅よりでかくなることが原因っぽいので、そこを修正します

**Comment by toratora-yaki** [comment]
承知しました、アドバイスありがとう!
