### ISSUE TITLE
QAitem　コンポーネントを作る。

### ISSUE THREAD

**Issue by tarou-jp** [Yadosai/official_site2024new#7]
<img width="330" alt="スクリーンショット 2024-04-14 18 20 38" src="https://github.com/Yadosai/official_site2024new/assets/117962902/b2c2fd61-7102-4d03-8d4d-d662adebc00c">

**Comment by nowex35** [comment]
![スクリーンショット 2024-04-21 104453](https://github.com/Yadosai/official_site2024new/assets/152232532/9d4a06c5-e8de-4e2e-9955-1237f6333bdd)
Aが薄すぎる
