### ISSUE TITLE
最終調整＆不具合修正用

### ISSUE THREAD

**Issue by tarou-jp** [Yadosai/official_site2024new#73]
変更点をコメントしていってください。

不具合の調整
画像を本番用のものに置き換える
・カレンダー画像
・マップピン画像

**Comment by tarou-jp** [comment]
企画itemの日付データ用propsを二日分別々に受け取るようにする

**Comment by tarou-jp** [comment]
5/17日までに変更点を上げといてください

**Comment by nowex35** [comment]
・パンフレットリンク添付（未提出）
・更新情報の更新（ホームページを更新しました）
・フッダーのインスタリンクを新歓垢から本アカに変更(https://www.instagram.com/yadokari_sai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==)
・「取材について」を追加したいですが追加でページつくるのできないのでパンフレットと同じようにダウンロードリンク貼るつもりです
→模擬店の出店時間は別に決まってないので両日か本祭のみにしました

**Comment by tarou-jp** [comment]
追加修正

協賛ページ
<img width="282" alt="スクリーンショット 2024-05-16 13 47 45" src="https://github.com/Yadosai/official_site2024new/assets/117962902/1cecda11-280b-466a-9236-cf5992c8402a">
スマホ用画面でtitleのfontsizeが小さくなってない。

pc用画面で協賛団体一覧の右に空間が開く。

**Comment by tarou-jp** [comment]
> ・パンフレットリンク添付（未提出） ・更新情報の更新（ホームページを更新しました） ・フッダーのインスタリンクを新歓垢から本アカに変更(https://www.instagram.com/yadokari_sai?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==) ・「取材について」を追加したいですが追加でページつくるのできないのでパンフレットと同じようにダウンロードリンク貼るつもりです →模擬店の出店時間は別に決まってないので両日か本祭のみにしました

これやってる時間ないので、べつissueでやってください。

**Comment by nowex35** [comment]
別イシューで埋め込みpdfのみできてないです。それ以外はプッシュしました。

**Comment by tarou-jp** [comment]
全ページでのページ遷移を完成させる。(アンカーリンクのやつ
)

**Comment by tarou-jp** [comment]
出演団体一覧で、模擬店情報いつの間にかなくなってたので付け足す。

**Comment by tarou-jp** [comment]
模擬店一覧ページのよくわからんclass="test"を消す
これ以上はやりません。

**Comment by tarou-jp** [comment]
<img width="1468" alt="スクリーンショット 2024-05-17 1 19 36" src="https://github.com/Yadosai/official_site2024new/assets/117962902/2e243695-d476-46ea-9c2a-4e7bf4b3bcba">
これこれ治すのはやりませんので、別issueで

**Comment by tarou-jp** [comment]
模擬店ページ、id順で並んでないのはなんでなんやろ

**Comment by tarou-jp** [comment]
<img width="277" alt="スクリーンショット 2024-05-17 1 31 45" src="https://github.com/Yadosai/official_site2024new/assets/117962902/a2bdbbad-ab20-485a-8a6d-329cd4e42a4c">

模擬店情報渡さない前提で作り替えたんかな
模擬店情報入れたら他の要素と重なる

**Comment by tarou-jp** [comment]
直接mainにpushしました。(どうせだれもレビューしないし)
